### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by kihana** [hms-networks/node-red-contrib-kolibri#14] opened 2021-01-25 15:16 UTC
Hello,

Could you give any ideas about why the connection was closed with 1006 code? Is it possible to fix it?

The connection to the broker established via proxy server. And both server and proxy are available at this time (25 Jan 16:18:32).

Messages from Node-RED log:
`22 Jan 15:03:01 - [info] Started flows`
`22 Jan 15:03:02 - [info] [kolibri-broker:2ad4f37.e924f0c] Logging in`
`22 Jan 15:03:02 - [info] [kolibri-broker:2ad4f37.e924f0c] Logged in`
`25 Jan 16:18:32 - [info] [kolibri-broker:2ad4f37.e924f0c] Connection closed with code = 1006`
`25 Jan 16:18:33 - [info] [kolibri-broker:2ad4f37.e924f0c] Connecting`
`25 Jan 16:18:34 - [info] [kolibri-broker:2ad4f37.e924f0c] Logging in`
`25 Jan 16:18:34 - [info] [kolibri-broker:2ad4f37.e924f0c] Logged in`

Also, sometimes the connection problem happens during the deploy of Node-RED flow. See 25 Jan 17:51:14 line in the log below:
`25 Jan 17:50:53 - [info] Stopping flows`
`25 Jan 17:50:53 - [info] [cronplus:4d8abe40.d3b04] Refreshing running schedules`
`25 Jan 17:50:53 - [info] [cronplus:c10f0f66.6433c] Refreshing running schedules`
`25 Jan 17:50:53 - [info] [cronplus:2c4d2dc6.378f52] Refreshing running schedules`
`25 Jan 17:50:53 - [info] [cronplus:68d3c72c.2ac8f8] Refreshing running schedules`
`25 Jan 17:50:53 - [info] [cronplus:1bec75bc.78da4a] Refreshing running schedules`
`25 Jan 17:50:53 - [info] [cronplus:8e25e922.0f43a8] Refreshing running schedules`
`25 Jan 17:50:53 - [info] [cronplus:fce626a2.4c83a8] Refreshing running schedules`
`25 Jan 17:50:53 - [info] [cronplus:fe566d1a.8004c] Refreshing running schedules`
`25 Jan 17:50:53 - [info] [kolibri-broker:2ad4f37.e924f0c] Closing connection`
`25 Jan 17:50:53 - [info] Stopped flows`
`25 Jan 17:50:53 - [info] Starting flows`
`25 Jan 17:50:53 - [info] [kolibri-broker:2ad4f37.e924f0c] Connecting`
`25 Jan 17:50:53 - [info] [cronplus:4d8abe40.d3b04] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 53 23 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:50:53 - [info] [cronplus:c10f0f66.6433c] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 05 17 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:50:53 - [info] [cronplus:2c4d2dc6.378f52] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 20 17 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:50:53 - [info] [cronplus:68d3c72c.2ac8f8] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 03 0 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:50:53 - [info] [cronplus:1bec75bc.78da4a] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 0 18 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:50:53 - [info] [cronplus:8e25e922.0f43a8] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 0 1 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:50:53 - [info] [cronplus:fce626a2.4c83a8] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 30 17 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:50:53 - [info] [cronplus:fe566d1a.8004c] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 06 0 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:50:53 - [info] Started flows`
`25 Jan 17:50:54 - [info] [kolibri-broker:2ad4f37.e924f0c] Logging in`
`25 Jan 17:50:55 - [info] [kolibri-broker:2ad4f37.e924f0c] Logged in`
`25 Jan 17:51:13 - [info] Stopping flows`
`25 Jan 17:51:13 - [info] [cronplus:4d8abe40.d3b04] Refreshing running schedules`
`25 Jan 17:51:13 - [info] [cronplus:c10f0f66.6433c] Refreshing running schedules`
`25 Jan 17:51:13 - [info] [cronplus:2c4d2dc6.378f52] Refreshing running schedules`
`25 Jan 17:51:13 - [info] [cronplus:68d3c72c.2ac8f8] Refreshing running schedules`
`25 Jan 17:51:13 - [info] [cronplus:1bec75bc.78da4a] Refreshing running schedules`
`25 Jan 17:51:13 - [info] [cronplus:8e25e922.0f43a8] Refreshing running schedules`
`25 Jan 17:51:13 - [info] [cronplus:fce626a2.4c83a8] Refreshing running schedules`
`25 Jan 17:51:13 - [info] [cronplus:fe566d1a.8004c] Refreshing running schedules`
`25 Jan 17:51:13 - [info] [kolibri-broker:2ad4f37.e924f0c] Closing connection`
`25 Jan 17:51:13 - [info] Stopped flows`
`25 Jan 17:51:13 - [info] Starting flows`
`25 Jan 17:51:13 - [info] [kolibri-broker:2ad4f37.e924f0c] Connecting`
`25 Jan 17:51:13 - [info] [cronplus:4d8abe40.d3b04] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 53 23 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:51:13 - [info] [cronplus:c10f0f66.6433c] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 05 17 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:51:13 - [info] [cronplus:2c4d2dc6.378f52] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 20 17 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:51:13 - [info] [cronplus:68d3c72c.2ac8f8] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 03 0 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:51:13 - [info] [cronplus:1bec75bc.78da4a] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 0 18 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:51:13 - [info] [cronplus:8e25e922.0f43a8] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 0 1 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:51:13 - [info] [cronplus:fce626a2.4c83a8] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 30 17 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:51:13 - [info] [cronplus:fe566d1a.8004c] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"0 06 0 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}`
`25 Jan 17:51:13 - [info] Started flows`
**25 Jan 17:51:14 - [error] [kolibri-broker:2ad4f37.e924f0c] Connection error: Unexpected server response: 403**
**25 Jan 17:51:14 - [info] [kolibri-broker:2ad4f37.e924f0c] Connection closed with code = 1006**
`25 Jan 17:51:15 - [info] [kolibri-broker:2ad4f37.e924f0c] Connecting`
`25 Jan 17:51:17 - [info] [kolibri-broker:2ad4f37.e924f0c] Logging in`
`25 Jan 17:51:17 - [info] [kolibri-broker:2ad4f37.e924f0c] Logged in`

The last version (0.3.1) is used.

**Comment by Danidaniani** [comment] 2021-01-26 08:04
Hello,

code 1006 stands for "websocket: close (abnormal closure)". 
This usually happens if the node-red client terminates its connection to the broker instead of properly closing it.
There are different reasons why this might happen. 

Node-red-contrib-kolibri implements a websocket based ping-pong mechanism in order to reset a keepalive-timer, as long as we receive those packages within its timeout interval. After reaching the timeout the connection will be closed abnormal (no close request). It might be possible that the internal timeout was reached for your first entry "25 Jan 16:18:32 - [info] [kolibri-broker:2ad4f37.e924f0c] Connection closed with code = 1006", due to a missing ping-pong response. I simply can reproduce your logs by interrupting the connection to the broker for a timespan of 20 seconds. Can you check if your connection is stable to both proxy and server? 

Receiving another error 1006 on "25 Jan 17:51:14"  is a consequence of the previous error 403 (HTTP 403 - forbidden). 

Please let me know if you connection issues are still not fixed and provide further information.

Regards

**Comment by kihana** [comment] 2021-01-27 07:14
Hello,

I checked the connection to server and proxy while disconnecting (25 Jan 16:18:32) with the ping tool. And they show that the connection is good. Ping passed without any loss.

**Comment by Danidaniani** [comment] 2021-02-03 12:55
Hello,

based on your information I can not tell clearly why this problem occurs. If you are working directly in the code, you can try to increase the timeout interval until node-red-kolibri terminates the connection (1006). 

Regards

**Comment by arbue** [comment] 2021-08-05 11:26
Closing this issue.

**Closed by arbue** 2021-08-05 11:26 UTC
